ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # 1. Odometry configuration from rf2o
    odom0: /odom_rf2o
    # [X, Y, Z, Roll, Pitch, Yaw, X_dot, Y_dot, Z_dot, Roll_dot, Pitch_dot, Yaw_dot, X_ddot, Y_ddot, Z_ddot]
    odom0_config: [true, true, false,
                   false, false, true,
                   true, false, false, # OPTIMIZED: Y_dot is FALSE (No lateral sliding/strafing)
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 15

    # 2. IMU configuration from Raspberry Pi
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true, false, false]
    imu0_queue_size: 15
    imu0_remove_gravitational_acceleration: true
